### ISSUE TITLE
Missing DXFs

### ISSUE THREAD

**Issue by Annex-Engineering** [VoronDesign/Voron-1#28]
Deleted.

**Comment by natewalck** [comment]
It seems rather one-sided that Annex can use any and all Voron designs, but Annex's EULA forbids the Voron project from using anything that comes out of the Annex repo (See: https://github.com/Annex-Engineering/VORON_Mods/blob/master/LICENSE.md). It is highly unlikely this "EULA" would ever stand up in court and is clearly posturing without the basis to do so. **Feeling** like you own an idea doesn't mean you actually own it legally or have any control over said idea.

I'm not part of the Voron Design team, however I wanted to point out that this behavior violates an implicit contract within open source.. Quid pro quo is expected for opensource projects and violating this means you really have no place in a community where we share designs and ideas freely. This kind of take-without-giving-back mindset is what poisons opensource communities. I've seen it happen on many other code-based projects and I'd hate to see it happen here.

**Comment by Coffee0297** [comment]
Its not for use internally in Annex so it has nothing to do with annex. The only reason the request went in is other people could use them. So not shure how it has anything to do with annex. 

-Tonny

**Comment by Annex-Engineering** [comment]
Your really missing the point. We were discussing on discord, and a friend of ours happened to be building a v1.8 hybrid machine and wanted some smoked acrylic panels. There are no sources for these, so someone internally offered to cut them. I'm sure there are other people with the same issue, who may or may not want to cut their own panels, and the files would help, cad or not.

**Comment by natewalck** [comment]
> Its not for use internally in Annex so it has nothing to do with annex. The only reason the request went in is other people could use them. So not shure how it has anything to do with annex.
> 
> -Tonny

You are right. I'm not sure why it has anything to do with Annex.

<img width="299" alt="Screen Shot 2020-09-06 at 3 31 50 PM" src="https://user-images.githubusercontent.com/867868/92333793-485b0600-f056-11ea-92ca-a8fa3b57e876.png">

**Comment by natewalck** [comment]
> Your really missing the point. We were discussing on discord, and a friend of ours happened to be building a v1.8 hybrid machine and wanted some smoked acrylic panels. There are no sources for these, so someone internally offered to cut them. I'm sure there are other people with the same issue, who may or may not want to cut their own panels, and the files would help, cad or not.

If someone in Voron wanted to do the same and opened a PR, would you also provide it to them? Based on the EULA, that answer would seem to be "no".

**Comment by Coffee0297** [comment]
> 
> 
> > Its not for use internally in Annex so it has nothing to do with annex. The only reason the request went in is other people could use them. So not shure how it has anything to do with annex.
> > -Tonny
> 
> You are right. I'm not sure why it has anything to do with Annex.
> 
> <img alt="Screen Shot 2020-09-06 at 3 31 50 PM" width="299" src="https://user-images.githubusercontent.com/867868/92333793-485b0600-f056-11ea-92ca-a8fa3b57e876.png">

There is a difference between voron community and voron internals. so depends. Voron internal is a commercial entity. The community is not. So community can do what they want. voron as a commercial entity can't

-Tonny

**Comment by Kirinkunhime** [comment]
What reason would there be not to provide missing files?

I've made a PCB which you can find in the Annex-repo (the Carabiner) and if the Voron-account opened an issue that some footprints for that are missing I'd gladly add them.

The EULA just states that commercial entities are not allowed to reproduce, sell and whatever, but they are free to open issues, that point out things like missing files.

To be honest, I don't understand the whole discussion here - someone pointed out that DXFs are missing. 
**This whole discussion of the EULA of Annex, does not contribute in any way to resolving the issue, so I'd love if we could all cease this & concentrate on the issue opened here on github.**
If you @natewalck are up for discussions on the matter, please drop a message on Discord & we can talk about things.

**Comment by natewalck** [comment]
> What reason would there be not to provide missing files?
> 
> I've made a PCB which you can find in the Annex-repo (the Carabiner) and if the Voron-account opened an issue that some footprints for that are missing I'd gladly add them.
> 
> The EULA just states that commercial entities are not allowed to reproduce, sell and whatever, but they are free to open issues, that point out things like missing files.
> 
> To be honest, I don't understand the whole discussion here - someone pointed out that DXFs are missing.
> **This whole discussion of the EULA of Annex, does not contribute in any way to this discussion, so I'd love if we could all cease this & concentrate on the issue opened here on github.**
> If you @natewalck are up for discussions on the matter, please drop a message on Discord & we can talk about things.

Can you link me to the Corp or LLC that Voron operates under? I am under the impression it is a group of people with a common interest, not a corporation that employs people for profit. If that impression is wrong, let me know.

**Comment by Peej11** [comment]
> To be honest, I don't understand the whole discussion here - someone pointed out that DXFs are missing.
> **This whole discussion of the EULA of Annex, does not contribute in any way to resolving the issue, so I'd love if we could all cease this & concentrate on the issue opened here on github.**

I don't think anyone has said they wouldn't be provided. It was possibly a simple oversight. That said, it's also probably a low priority as well. In the meantime, anyone is able to submit a PR and add them if they choose.

>dxf files are missing for the following:
>* Deck Panel (both sizes)
>* Rear Panel (both sizes)
>* Bottom Panel (both sizes)
>* Electronics Box Panels (300 size)

It looks like @Annex-Engineering accidentally deleted the original issue. So here it is for tracking purposes. This is also visible under edit history to the original comment.
