### ISSUE TITLE
Bed size

### ISSUE THREAD

**Issue by otrava** [VoronDesign/Voron-1#44]
There is also a drawing for the bed in the document for voron 2.4. I didn't find this drawing anywhere in the documentation for Voron 1.8, so I can't continue the construction. The size as such I know is 300x300x8 mm but I am concerned with the mounting holes and their location. Would it be possible to add it to the documentation? Thank you in advance
PS I apologize for my English

**Comment by J4CKT** [comment]
I just had the same problem - it's a sticky in the voron_v1_questions channel.

300 Bed Drawing:
https://media.discordapp.net/attachments/551488536256184331/703610957695287316/image0.png?width=623&height=593

250 Bed Drawing: 
https://cdn.discordapp.com/attachments/551488536256184331/703610958165311568/image1.png

**Comment by eddietheengineer** [comment]
https://github.com/VoronDesign/Voron-1/tree/Voron1.8/Drawings

The drawings are now on Github!
