### ISSUE TITLE
Exhaust filter cutout too short

### ISSUE THREAD

**Issue by bartlammers** [VoronDesign/Voron-1#49]
In the CAD of the V1 the cutout for the exhaust filter is too short (35.6mm instead of 42mm of the V2). This carries through in the generated drawings of the top back panel. People might have gotten panels ordered or cut with a hole that's not big enough. (I have, but that doesn't matter 😄 )

**Comment by bartlammers** [comment]
![image](https://user-images.githubusercontent.com/12411803/107125859-9053b280-68ac-11eb-917e-2b8d9f23731a.png)
V1


![image](https://user-images.githubusercontent.com/12411803/107125863-947fd000-68ac-11eb-8236-18a7489e14a4.png)
V2

**Comment by CircuitGuy** [comment]
I'm not certain, but I think @eddietheengineer has a fix for this in PR #55

**Comment by bartlammers** [comment]
Yes looks like it, thanks @eddietheengineer ;)

**Comment by raymondh2** [comment]
Closed by #55
