### ISSUE TITLE
Not enough small bearing spacer

### ISSUE THREAD

**Issue by pasarn** [VoronDesign/Voron-1#5]
Hi Voron Team,

i have seen, i need 6 small bearing spacer. 4 for the A/B drive unit (Page 8 in the Manual) and 2 for the front idlers (Page 20 in the Manual).
From the STL filename i need 4.
`small_bearing_spacer_x4.stl`

**Comment by Kriechi** [comment]
Yes - I just found the same issue. We had the same problem with the large spacers...
@volcom8190 would you mind renaming the file to `_x6.stl`?

**Comment by Annex-Engineering** [comment]
fixed

[https://github.com/VoronDesign/Voron-1/commit/a414b2aa882f4c5cc4afbbd3ea69597b5ac1bb81](url)
