### ISSUE TITLE
Some exhaust filter accented part filenames do not start with [a]_

### ISSUE THREAD

**Issue by masimplo** [VoronDesign/Voron-1#58]
Exhaust filter grill shows as red in the master cad file but is not denoted as accented in the filename.
https://github.com/VoronDesign/Voron-1/blob/Voron1.8/STLs/Exhaust_Filter/exhaust_filter_grill.stl

Same for the exhaust mount clips:
https://github.com/VoronDesign/Voron-1/blob/Voron1.8/STLs/Exhaust_Filter/exhaust_filter_mount_x2.stl

![exhaust filter](https://user-images.githubusercontent.com/803983/115598320-f2845700-a2e2-11eb-829d-8f237f668731.PNG)

For the mount clips I see there is the same issue in the v2 repo also:
https://github.com/VoronDesign/Voron-2/issues/224

**Comment by raymondh2** [comment]
It doesn't really matter as either works well.
