### ISSUE TITLE
STL latch needed 1 time instead of 2

### ISSUE THREAD

**Issue by degraafm76** [VoronDesign/Voron-1#59]
\Voron-1-1.8r1\Voron-1-1.8r1\STLs\Panel_Mounting\Front_Doors\latch_x2.stl should be printed once according to the CAD. Filename should be changed to latch.stl

**Comment by raymondh2** [comment]
Two is correct. One on top and bottom.

**Comment by degraafm76** [comment]
No not for the 1.8. Please look at the master CAD. Bottom is closed with handle_bottom_left and handle_bottom_right. No latch is used.

**Comment by degraafm76** [comment]
> Two is correct. One on top and bottom.

No not for the 1.8. Please look at the master CAD. Bottom is closed with handle_bottom_left and handle_bottom_right. I'm 100% sure no latch is used for bottom handles. The bottom handles are closed with 3 magnets in the handles.

![image](https://user-images.githubusercontent.com/1271011/116004546-6e441380-a603-11eb-8f35-2ce530bef635.png)

**Comment by raymondh2** [comment]
No it is still correct. The bottom handles just magnets to latch to the latch part just like the top handles

**Comment by degraafm76** [comment]
I'm 100% sure it isnt the case ;-) please take a look at the master CAD and my previous screenshot. The bottom latch would also interfere with the LCD display.

**Comment by dubjay2k** [comment]
Confirming I only used one latch for my build, and that was at the top, where it holds magnets for the top two door handles.
