### ISSUE TITLE
1.8r1 release missing many STL

### ISSUE THREAD

**Issue by jltx1** [VoronDesign/Voron-1#61]
I downloaded the official release and discovered it is missing many STL parts.  For example, the front doors are missing from panel mount directory, among other missing.

**Comment by dubjay2k** [comment]
The official release would be under the `Voron1.8` branch.  It sounds like you were looking at one of the tags.

**Comment by jltx1** [comment]
I used this and I know others are as well:

https://github.com/VoronDesign/Voron-1/releases/tag/V1.8r1

**Comment by dubjay2k** [comment]
By default - when you visit https://github.com/VoronDesign/Voron-1 - you're in the `Voron1.8` branch. Where was that URL linked from?  They should update it.

**Comment by jltx1** [comment]
from that exact repository.  For all GitHub projects they list the latest official release on the front page.  You never want to grab head unless you know what you are doing.

**Comment by dubjay2k** [comment]
![image](https://user-images.githubusercontent.com/47653652/116458392-76759c00-a819-11eb-816a-7005cfa3c926.png)
I'm seeing the front doors here.  What are the other ones that were missing?

**Comment by jltx1** [comment]
I know (now) that they are in the main repository.  I downloaded the official release asset package which was clearly a mistake.  I was just pointing it out so it can be fixed so others don't run into it.

**Comment by dubjay2k** [comment]
My screenshot above is from the `V1.8r1` release tag, and I'm seeing the front doors there. That was one of the STL groups that you mentioned was missing.
